[package]
name = "railgun-broadcaster"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { version = "0.9" }
structopt = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "parking_lot"] }
tracing-logfmt = { version = "0.3" }
axum = { workspace = true }

config = { path = "../../crates/config" }
broadcaster-core = { workspace = true }
poi = { workspace = true }
waku-relay = { workspace = true }
broadcaster-service = { path = "../../crates/service" }
railgun-wallet = { workspace = true }
sync-service = { workspace = true }
local-db = { workspace = true }
reqwest = { workspace = true }
